name: example
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  secure_session:
    path: ../

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
