name: secure_session
description: A secure session manager for Dart.
version: 1.0.0
repository: https://github.com/avesbox/secure_session

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  crypto: ^3.0.6
  encrypt: ^5.0.3

executables:
  generate_key: