name: secure_session
description: Secure stateless cookie session for Dart. It is a simple and secure way to manage user sessions in web applications.
version: 1.0.5
repository: https://github.com/avesbox/secure_session
topics:
  - secure
  - session
  - http
  - server

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  crypto: ^3.0.6
  encrypt: ^5.0.3

executables:
  generate_key: